### ISSUE TITLE
Test the model

### ISSUE THREAD

**Issue by Nerdyvedi** [aigagror/wasserstein-style-transfer#2]
Hi,
Great work!

Could you let me know if there is a way to save the trained model and test it. Everytime I run main.py, it starts training the model.
I want to load the pretrained model and then only test it.

Thank you

**Comment by aigagror** [comment]
Hey Nerdyvedi,
It actually doesn't make any sense to save the trained model. Training the model **is** part of the transfer process. For every style image and generated image, you need to train the model, particularly the discriminator to differentiate between the style features and the generated features.

This is the tradeoff with Wasserstein style transfer. We get higher quality styles, but at the cost of more computation
